---
sources:
    # Jacob's stuff
    - name: remake/remodel
      type: weblog
      owner: jacob
      url: http://chompy.net/blogs/jacob/
      feed_url: http://chompy.net/blogs/jacob/feeds/index.atom
      
    - name: dark entries
      type: linklog
      owner: jacob
      url: http://chompy.net/blogs/jacob/darkentries/
      feed_url: http://chompy.net/blogs/jacob/feeds/darkentries.atom

    - name: cobralibre
      type: twitter
      owner: c.libre
      url: http://twitter.com/cobralibre 
    
    - name: golden hours
      type: tumblelog
      owner: c.libre
      url: http://golden.cpl593h.net/
      
    - name: cobra libre's photostream
      type: photostream
      owner: cobra libre
      flickr_id: 35034350056@N01
      url: http://www.flickr.com/photos/cobra/
      
    # Tamara's stuff
    - name: peeny wally
      type: weblog
      owner: pogo
      url: http://chompy.net/blogs/pogo/
      feed_url: http://chompy.net/blogs/pogo/atom.xml
      
    - name: The Longest Train I Ever Saw
      type: tumblelog
      owner: pogo
      url: http://thelongesttrainieversaw.tumblr.com/
      
    - name: tiddly links
      type: linklog
      owner: pogo
      url: http://www.chompy.net/blogs/pogo/links/
      feed_url: http://www.chompy.net/blogs/pogo/links/atom.xml
      
    - name: pogococonino
      type: twitter
      owner: pogo
      url: http://twitter.com/pogococonino
    
    - name: pogo coconino's photostream
      type: photostream
      owner: pogo coconino
      flickr_id: 98698771@N00
      url: http://www.flickr.com/photos/pogococonino/
      
    # Mike's stuff
    - name: distiller cobbler cabinetmaker
      type: tumblelog
      owner: sentry
      url: http://industry.tumblr.com/
      
    - name: tenorune
      type: twitter
      owner: sentry
      url: http://twitter.com/tenorune
      
    - name: tenorune's photostream
      type: photostream
      owner: tenorune
      flickr_id: 98749297@N00
      url: http://www.flickr.com/photos/lightseed/
      
    # Hazel's stuff
    - name: Spinning Away
      type: weblog
      owner: Fortunate Hazel
      url: http://chompy.net/blogs/chris/
      feed_url: http://chompy.net/blogs/chris/atom.xml
    
    - name: Lord Ragdoll Kitten's photostream
      type: photostream
      owner: Lord Ragdoll Kitten
      flickr_id: 46348833@N00
      url: http://www.flickr.com/photos/46348833@N00/
    
    # Nathalie's stuff
    - name: a tiger pounces on my heart
      type: weblog
      owner: Nathalie
      url: http://chompy.net/blogs/nathalie/
      feed_url: http://chompy.net/blogs/nathalie/atom.xml
      
    - name: CHO2007's photostream
      type: photostream
      owner: CHO2007
      flickr_id: 28183076@N00
      url: http://www.flickr.com/photos/nathalie/
    
    # Seth's stuff
    - name: Carefully Selected Garbage
      type: weblog
      owner: Seth
      url: http://www.carefullyselectedgarbage.com/
      feed_url: http://www.carefullyselectedgarbage.com/feeds/posts/default

    - name: setholdmixon
      type: twitter
      owner: Seth
      url: http://twitter.com/setholdmixon
      
    - name: setholdmixon's photostream
      type: photostream
      owner: setholdmixon
      flickr_id: 30872993@N00
      url: http://www.flickr.com/photos/setholdmixon/
    
    # Sarah Looney's stuff
    # - name: saraholdmixon
    #   type: twitter
    #   owner: Sarah
    #   url: http://twitter.com/saraholdmixon
      
    - name: sarahloo's photostream
      type: photostream
      owner: sarahloo
      flickr_id: 66594479@N00
      url: http://www.flickr.com/photos/sarahloo/
    
    # Sarah Knight's stuff
    - name: cyndi laupest's photostream
      type: photostream
      owner: cyndi laupest
      flickr_id: 78616686@N00
      url: http://www.flickr.com/photos/78616686@N00/
    
    # Scott Talkington's stuff
    - name: junklab's photostream
      type: photostream
      owner: junklab
      flickr_id: 24472191@N00
      url: http://www.flickr.com/photos/junklab/
    
    # Dakota's stuff
    - name: del.icio.us/dakotasmith
      type: linklog
      owner: Dakota
      url: http://del.icio.us/dakotasmith
      feed_url: http://del.icio.us/rss/dakotasmith
    
    - name: dakotasmith
      type: twitter
      owner: Dakota
      url: http://twitter.com/dakotasmith
      
    - name: dakota smith's photostream
      type: photostream
      owner: dakota smith
      flickr_id: 51379940@N00
      url: http://www.flickr.com/photos/dakotasmith/
    
    # Smason's stuff
    - name: Rubbish, With Occasional Music
      type: weblog
      owner: Sean
      url: http://www.headcrab.org/
      feed_url: http://www.headcrab.org/feed/atom/
    
    - name: del.icio.us/seanmason
      type: linklog
      owner: Sean
      url: http://del.icio.us/seanmason
      feed_url: http://del.icio.us/rss/seanmason
      
    - name: pusgums' photostream
      type: photostream
      owner: pusgums
      flickr_id: 29193619@N00
      url: http://www.flickr.com/photos/smason/
      
    # Karla's stuff
    - name: Confessions of a Grade School Role Model
      type: weblog
      owner: Karla
      url: http://savagepencil.typepad.com/confessions/
      feed_url: http://savagepencil.typepad.com/confessions/index.rdf
      
    - name: Charlie Letters
      type: weblog
      owner: Karla
      url: http://savagepencil.typepad.com/
      feed_url: http://savagepencil.typepad.com/charlieletters/index.rdf
      
    - name: iamedithpiaf's photostream
      type: photostream
      owner: iamedithpiaf
      flickr_id: 89984665@N00
      url: http://www.flickr.com/photos/89984665@N00/
      
    # Alan Hampton's stuff
    - name: austin tx's photostream
      type: photostream
      owner: austin tx
      flickr_id: 33356186@N00
      url: http://www.flickr.com/photos/austintx/
    
    # Spaceship No Future
    - name: Spaceship No Future
      type: weblog
      owner: SNF Labs
      url: http://www.spaceshipnofuture.org/
      feed_url: http://www.spaceshipnofuture.org/grueyorktimes/feeds/atom.xml

    - name: Grue York Times Letters to the Editor
      type: commentlog
      owner: SNF Labs
      url: http://www.spaceshipnofuture.org/grueyorktimes/
      feed_url: http://www.spaceshipnofuture.org/grueyorktimes/feeds/comments.atom.xml

    - name: 15 Ways
      type: weblog
      owner: SNF Labs
      url: http://www.spaceshipnofuture.org/15ways/
      feed_url: http://www.spaceshipnofuture.org/15ways/feeds/atom/

    - name: 15 Ways Comments
      type: commentlog
      owner: SNF Labs
      url: http://www.spaceshipnofuture.org/15ways/comments/
      feed_url: http://www.spaceshipnofuture.org/15ways/feeds/atom/comments

#    - name: CHOMP
#      url: http://www.spaceshipnofuture.org/ubb/
    
    - name: link-o-matic
      type: linklog
      owner: SNF Labs
      url: http://www.spaceshipnofuture.org/linkomatic/
      feed_url: http://www.spaceshipnofuture.org/linkomatic/feeds/atom/

    - name: link-o-matic comments
      type: commentlog
      owner: SNF Labs
      url: http://www.spaceshipnofuture.org/linkomatic/comments/
      feed_url: http://www.spaceshipnofuture.org/linkomatic/feeds/atom/comments
    
#    - name: Shoplifters, Unite
#      type: linklog
#      owner: SNF Labs
#      url: http://www.spaceshipnofuture.org/shoplifters/
#      feed_url: http://www.spaceshipnofuture.org/shoplifters/feeds/atom/
    