#!/bin/sh

if [ -d $HOME/bin ]; then
    SCRIPTS_DIR="$HOME/bin"
elif [ -d $HOME/Scripts ]; then
    SCRIPTS_DIR="$HOME/Scripts"
else
    echo "A scripts directory couldn't be found!"
    exit 1
fi

if [ -d $HOME/backwater ]; then
    BW_DIR=$HOME/backwater
elif [ -d $HOME/Scripts ]; then
    BW_DIR=$SCRIPTS_DIR/backwater
else
    echo "A backwater directory couldn't be found!"
    exit 1
fi
BW_DATA_DIR=$BW_DIR/data

echo Validating HTML 5 output...
$SCRIPTS_DIR/html5check -x $BW_DATA_DIR/output/chompy.html
echo

echo Validating main feed...
$SCRIPTS_DIR/feedcheck $BW_DATA_DIR/output/chompy.atom
echo

echo Validating links feed...
$SCRIPTS_DIR/feedcheck $BW_DATA_DIR/output/links.atom
echo
